name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ sqlite3 libsqlite3-dev

      - name: Configure project
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          cmake --build .
